
import java.io.File; // import the java File
import java.io.FileWriter; // import FileWriter
import java.io.IOException; // import the io exception
import java.io.PrintWriter; // import PrintWriter
import java.util.Scanner; // import the scanner

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aairah Ahmeed
 */
public class Info extends javax.swing.JFrame { // info class extends the jframe

    /**
     * Creates new form Info
     */
    public Info() { // beginning the Info class
        initComponents(); // the components in it
        formatTextArea(); // format the text area component
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton1.setText("Submit >");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("Please enter your name:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("Check");

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton2.setText("Continue >");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Cases:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Verdict:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(188, 188, 188))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(22, 22, 22))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Results().setVisible(true); // set the next page as visible
        this.setVisible(false); // make this page invisible
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        saveVerdicts(); // Save the user's answers to the file
        displayCases(); // show the cases in the left text box
        displayVerdicts(); // show the saved answers in the right text box
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Gets the user's name and their answers, then writes it to "verdict.txt"
     */
    public void saveVerdicts() { // begin the verdict method
        try { // try the code below
            String name = jTextField1.getText(); // Get the name that the user typed into the text box
            // Open the file and add to the end instead of deleting previous text
            FileWriter w = new FileWriter ("verdict.txt", true); // create the file writer for the verdict.txt file
            PrintWriter fileOutput = new PrintWriter(w); // create the printwriter for the filewriter
            // Write the user's name
            fileOutput.print(name + "'s Answers: \n"); // add the users name to the file to sepearte the answers
            // Go through each case stored in the MainMenu program
            for (int i = 0; i < MainMenu.cases.length; i++) { // go through the code below so long as the file has a next line
                String caseName = MainMenu.cases[i].verdict.getCaseName(); // store the case name form the array in a string variable
                String verdictStatus = MainMenu.cases[i].verdict.getStudentVerdict(); // store the student verdict from the array in a string variable
                String reason = MainMenu.cases[i].verdict.getReason(); // store the student reason from the array in a String variable
                // Write the case details into the file
                fileOutput.print("Case " + (i + 1) + ": " + caseName); // Print the case number
                fileOutput.print("\t Verdict: " + verdictStatus); // print the verdict
                fileOutput.print("\t Reason: " + reason); // print the reason
                fileOutput.println(" "); // print a spacing for formatting
            } // close the for loop
            fileOutput.println(" -------------- "); // print for formatting
            fileOutput.close(); // // Close the file when finished saving

        } catch (IOException e) { // catch the io exception if there is one
            System.out.println("Error writing to verdict.txt"); // Error message
        } // close the try-catch
    } // close the method
    
    /**
     * Method to polymorphically display all saved cases in the text area by
     * fetching their specific toString data from the array.
     */
    public void displayCases() { // beginning of method to display the cases
        jTextArea1.setText(""); // clear the text area to prevent duplicating text on multiple clicks
        int count = 1; // create a case number counter, initializing it to 1

        try { // try the code block below to safeguard against potential array issues
            for (int i = 0; i < MainMenu.cases.length; i++) { // loop through the entire cases array
                if (MainMenu.cases[i] != null) { // check if the current array index contains a valid object

                    String caseDetails = MainMenu.cases[i].toString(); // polymorphic call to automatically fetch the correct child class toString text
                    jTextArea1.append( // append the formatted case information into the jTextArea1
                        "Case " + count + // append the case and number
                        "\n" + caseDetails + "\n\n" // display the unique text returned from the object's toString method
                    ); // close the append method
                    
                    count++; // increment the case number counter by 1
                } // end the if statement for null checking
            } // close the for loop
        } catch (Exception exception) { // catch general exceptions to ensure stability
            System.out.print("Error displaying cases: " + exception.getMessage()); // if caught, display an error message to console
        } // close the try-catch block
    } // close the displayCases method
    
    /**
     * Method to display all the verdicts from the file 
     */
    public void displayVerdicts(){ // begin the method to displayVerdicts
        try { // try the code below to check for runtime errors
            Scanner fileinput = new Scanner (new File ("verdict.txt")); // create a scanner object for the file cases
            while (fileinput.hasNext()){ // while the file has a next line
                String output = fileinput.nextLine(); // input the line into a String
                jTextArea2.append(output + "\n\n"); // append the string with formatting into the text area
            } // close the while loop
            fileinput.close(); // close the scanner
        } catch (IOException ioException) { // catch for an io exception
            System.out.print("Error: IO Exception"); // if caught, display an error message
        } // close the try-catch
    } // close the method

    public void formatTextArea() { // create a method to format the text area (no return and no parameter) 
        jTextArea1.setEditable(false); // make it uneditable
        jTextArea1.setBackground(null); // make the backround null
        jTextArea1.setOpaque(false); // make the background not opaque
        jTextArea1.setBorder(null); // make the borders null
        jTextArea1.setLineWrap(true); // make the line wrap true
        jTextArea1.setWrapStyleWord(true); // make the wrap style true
        
        jTextArea2.setEditable(false); // make it uneditable
        jTextArea2.setBackground(null); // make the backround null
        jTextArea2.setOpaque(false); // make the background not opaque
        jTextArea2.setBorder(null); // make the borders null
        jTextArea2.setLineWrap(true); // make the line wrap true
        jTextArea2.setWrapStyleWord(true); // make the wrap style true
    } // close the method
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
